import React, { useState } from "react";

const apiBaseUrl = import.meta.env.VITE_API_BASE_URL || "http://localhost:3000";
const defaultPhotos = {
  Dog: { Male: "https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=900&q=85", Female: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=900&q=85" },
  Cat: { Male: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=900&q=85", Female: "https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&w=900&q=85" },
};
const fallbackPhoto = pet => pet.photoUrl || defaultPhotos[pet.species]?.[pet.sex] || defaultPhotos[pet.species]?.Female || defaultPhotos.Dog.Female;
function Field({ label, value, setValue, type = "text", choices }) { return <label className="field"><small>{label}</small>{choices ? <select value={value} onChange={event => setValue(event.target.value)}>{choices.map(choice => <option key={choice}>{choice}</option>)}</select> : <input type={type} value={value} onChange={event => setValue(event.target.value)} />}</label>; }

export default function ManagePet({ pet, setPage }) {
  const [name, setName] = useState(pet.name || ""); const [species, setSpecies] = useState(pet.species || "Dog"); const [age, setAge] = useState(pet.age || ""); const [weight, setWeight] = useState(pet.weight || ""); const [color, setColor] = useState(pet.color || ""); const [sex, setSex] = useState(pet.sex || "Unknown"); const [photoUrl, setPhotoUrl] = useState(pet.photoUrl || ""); const [file, setFile] = useState(null); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const previewPet = { ...pet, species, sex, photoUrl };
  function choosePhoto(event) { const selected = event.target.files?.[0]; if (!selected) return; if (!selected.type.startsWith("image/") || selected.size > 5 * 1024 * 1024) { setMessage("Choose a JPG, PNG, or WebP image up to 5 MB."); return; } setFile(selected); setPhotoUrl(URL.createObjectURL(selected)); setMessage(""); }
  async function save() { setSaving(true); setMessage(""); try { let savedPhotoUrl = photoUrl; if (file) { const form = new FormData(); form.append("photo", file); const uploaded = await fetch(`${apiBaseUrl}/api/uploads`, { method: "POST", credentials: "include", body: form }); const uploadData = await uploaded.json(); if (!uploaded.ok) throw new Error(uploadData.message || "Could not upload photo"); savedPhotoUrl = `${apiBaseUrl}${uploadData.photoUrl}`; } const response = await fetch(`${apiBaseUrl}/api/pets/${pet._id || pet.id}`, { method: "PUT", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, species, age, weight, color, sex, photoUrl: savedPhotoUrl }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Could not update pet"); Object.assign(pet, data.pet); setPage("detail"); } catch (error) { setMessage(error.message || "Could not update pet"); } finally { setSaving(false); } }
  return <><header className="header"><button onClick={() => setPage("detail")}>‹</button><b>Manage Pet</b><span /></header><main className="form manage-pet-form"><h2>Edit {pet.name}</h2><label className="pet-editor-photo" htmlFor="edit-pet-photo" style={{ backgroundImage: `url(${fallbackPhoto(previewPet)})` }}><span>Change photo</span><input id="edit-pet-photo" type="file" accept="image/jpeg,image/png,image/webp" onChange={choosePhoto} /></label><h2>Pet details</h2><Field label="Pet name" value={name} setValue={setName} /><div className="split"><Field label="Species" value={species} setValue={setSpecies} choices={["Dog", "Cat"]} /><Field label="Age" value={age} setValue={setAge} /></div><Field label="Weight (kg)" type="number" value={weight} setValue={setWeight} /><div className="split"><Field label="Color" value={color} setValue={setColor} /><Field label="Sex" value={sex} setValue={setSex} choices={["Female", "Male", "Unknown"]} /></div>{message && <p className="auth-error">{message}</p>}<button className="button manage-save" disabled={saving} onClick={save}>{saving ? "Saving..." : "Save pet details"}</button></main></>;
}
